function createObj() {
    Cards = [
        new Card(2, "img/cards/C2.svg", false),
        new Card(2, "img/cards/D2.svg", false),
        new Card(2, "img/cards/H2.svg", false),
        new Card(2, "img/cards/S2.svg", false),
        new Card(3, "img/cards/C3.svg", false),
        new Card(3, "img/cards/D3.svg", false),
        new Card(3, "img/cards/H3.svg", false),
        new Card(3, "img/cards/S3.svg", false),
        new Card(4, "img/cards/C4.svg", false),
        new Card(4, "img/cards/D4.svg", false),
        new Card(4, "img/cards/H4.svg", false),
        new Card(4, "img/cards/S4.svg", false),
        new Card(5, "img/cards/C5.svg", false),
        new Card(5, "img/cards/D5.svg", false),
        new Card(5, "img/cards/H5.svg", false),
        new Card(5, "img/cards/S5.svg", false),
        new Card(6, "img/cards/C6.svg", false),
        new Card(6, "img/cards/D6.svg", false),
        new Card(6, "img/cards/H6.svg", false),
        new Card(6, "img/cards/S6.svg", false),
        new Card(7, "img/cards/C7.svg", false),
        new Card(7, "img/cards/D7.svg", false),
        new Card(7, "img/cards/H7.svg", false),
        new Card(7, "img/cards/S7.svg", false),
        new Card(8, "img/cards/C8.svg", false),
        new Card(8, "img/cards/D8.svg", false),
        new Card(8, "img/cards/H8.svg", false),
        new Card(8, "img/cards/S8.svg", false),
        new Card(9, "img/cards/C9.svg", false),
        new Card(9, "img/cards/D9.svg", false),
        new Card(9, "img/cards/H9.svg", false),
        new Card(9, "img/cards/S9.svg", false),
        new Card(10, "img/cards/C10.svg", false),
        new Card(10, "img/cards/D10.svg", false),
        new Card(10, "img/cards/H10.svg", false),
        new Card(10, "img/cards/S10.svg", false),
        new Card(10, "img/cards/JC.svg", false),
        new Card(10, "img/cards/JD.svg", false),
        new Card(10, "img/cards/JH.svg", false),
        new Card(10, "img/cards/JS.svg", false),
        new Card(10, "img/cards/QC.svg", false),
        new Card(10, "img/cards/QD.svg", false),
        new Card(10, "img/cards/QH.svg", false),
        new Card(10, "img/cards/QS.svg", false),
        new Card(10, "img/cards/KC.svg", false),
        new Card(10, "img/cards/KD.svg", false),
        new Card(10, "img/cards/KH.svg", false),
        new Card(10, "img/cards/KS.svg", false),
        new Card(11, "img/cards/AC.svg", true),
        new Card(11, "img/cards/AD.svg", true),
        new Card(11, "img/cards/AH.svg", true),
        new Card(11, "img/cards/AS.svg", true),
    ]

}